config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get "sitemap", to: "sitemap#index", format: "xml", as: :sitemap_xml

  root as: "root_without_locale", to: "application#root_without_locale"

  scope ":locale", locale: /#{I18n.available_locales.map(&:to_s).join("|")}/ do
    root to: "pages#index"
    controller :pages do
      get "about-us", action: "about_us"
      get "faq", action: "faq"
      get "contact", action: "contact"
      get "terms-and-conditions", action: "terms_and_conditions", as: :terms_and_conditions
    end

    controller "forms" do
      post "contact-request", action: "contact_request"
    end
    scope "services", controller: "services" do
      root action: "index", as: :services
      get ":id", action: :show, as: :service
    end
  end

  match "*url", to: "application#render_not_found", via: [:get, :post, :path, :put, :update, :delete]
end

app/models/pages/services.rb
module Pages
  class Services < Cms::Page
    def url(locale = I18n.locale)
      "/#{locale}/services"
    end
  end
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :published

  globalize :name, :short_description, :url_fragment, :content

  image :banner, styles: {xxl: "2100x750#", thumb: "210x75#"}
  image :avatar, styles: { avatar: "400x400#", thumb: "100x100" }

  boolean_scope :published
  scope :sort_by_sorting_position, -> { order("sorting_position asc") }

  has_cache do
    pages :sitemap_xml, :home, :services, Service.all
  end


  has_seo_tags
  has_sitemap_record

  after_create :initialize_sorting_position

  def url(locale = I18n.locale)
    url_fragment = self.translations_by_locale[locale.to_sym].try(:url_fragment)
    if url_fragment.blank?
      return nil
    end
    "/#{locale}/services/#{url_fragment}"
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :initialize_service, only: [:show]
  caches_page :index, :show

  def index
    @services = Service.published.sort_by_sorting_position
    set_page_metadata(:services)
    initialize_locale_links
  end

  def show
    @another_header = true
    #@service = Service.first
    @banner = {}
    @banner[:image_url] = @service.banner.url(:xxl) if @service.banner.exists?
    @services = Service.published.sort_by_sorting_position

    @prev = @service.prev(@services)
    @next = @service.next(@services)
  end

  private
  def initialize_service
    @service = Service.published.joins(:translations).where(service_translations: { url_fragment: params[:id], locale: params[:locale] } ).first
    if @service.nil?
      return render_not_found
    end
    set_page_metadata(@service)
    initialize_locale_links
  end
end

app/views/services/index.html.slim
.services-wrapper
  .bottom-img style="background-image: url(#{asset_path('photos/bottom-services.jpg')})"
  .row
    .columns
      .text-center
        h2.header
          = t("services.title")
        p.under-section-header
          = t("services.description")
      .squares-wrapper
        .row.collapse
          - if @services.try(:any?)
            - @services.each_with_index do |service, index|
              .large-3.medium-4.small-6.columns.service
                = render "service", service: service, service_index: index

app/views/services/show.html.slim
.popup-social
  .social-container
    a href="#"
      = inline_svg "icons/share-fb.svg"
    a href="#"
      = inline_svg "icons/share-google.svg"
    a href="#"
      = inline_svg "icons/share-twitter.svg"
    .close-popup
      = inline_svg "icons/cross.svg"
.service-wrapper
  .banner
    - banner_image_url = @banner[:image_url] || asset_path('photos/banner-service.jpg')
    .img style="background-image: url(#{banner_image_url})"
    .png style="background-image: url(#{asset_path('photos/pattern.png')})"
    .frame
    .text-center
      - services_url = (services_page = Pages.services).try(:url).present? ? services_page.url : services_page.try(:default_url)
      a.title href=services_url
        = t("service.services-link")
      p.header
        = @service.name
      .share
        = inline_svg "icons/share.svg"
  .main-wrapper
    a.left-nav-container href=@prev.url
      span.number
        = @prev.sorting_position
      p
        = @prev.name
      .arrow
        = inline_svg "icons/arrow-left.svg"
        span
          = t("prev")
    a.right-nav-container href=@next.url
      span.number
        = @next.sorting_position
      p
        = @next.name
      .arrow
        = inline_svg "icons/arrow-right.svg"
        span
          = t("next")
    .row.collapse
      .columns
        .text-wrapper
          = raw @service.content
    .row
      .columns
        h2.section-header
          = t("service.other-services")

  - if @services.try(:any?)
    .carousel-container
      .navigation
        .carousel-slider-prev
          = inline_svg "icons/arrow-left.svg"
        .carousel-slider-next
          = inline_svg "icons/arrow-right.svg"
      ul.carousel
        - @services.each_with_index do |service, index|
          li
            = render "service", service: service, service_index: index

app/views/services/show2.html.slim
.popup-social
  .social-container
    a href="#"
      = inline_svg "icons/share-fb.svg"
    a href="#"
      = inline_svg "icons/share-google.svg"
    a href="#"
      = inline_svg "icons/share-twitter.svg"
    .close-popup
      = inline_svg "icons/cross.svg"
.service-wrapper
  .banner
    .img style="background-image: url(#{asset_path('photos/banner-service.jpg')})"
    .png style="background-image: url(#{asset_path('photos/pattern.png')})"
    .frame
    p.big-number 1
    .text-center
      p.title services
      p.header wealth structuring
      .share
        = inline_svg "icons/share.svg"
  .main-wrapper
    a.left-nav-container href="#"
      span.number 7
      p
        | family
        br
        | office
      .arrow
        = inline_svg "icons/arrow-left.svg"
        span prev
    a.right-nav-container href="#"
      span.number 2
      p
        | succession
        br
        | planning
      .arrow
        = inline_svg "icons/arrow-right.svg"
        span next
    .row.collapse
      .columns
        .text-wrapper
          p.title wealth structuring and asset protection
          p.regular ELGIN provides comprehensive advice on how to structure and protect your assets, ensure tax efficiency and long-term succession planning. ELGIN applies extensive experience as well as that of trusted partners worldwide to review and set up effective wealth protection mechanisms that safeguard what matters most to you and your family. ELGIN delivers tailor-made solutions based on your specific needs and circumstances.
          p.regular Importance of your privacy is the priority and your personal and financial information is dealt with the highest degree of confidentiality. Analysis of your unique risks and concerns are the starting point of a tailor made plan in order to eliminate the likelihood of wealth being depleted. ELGIN is particularly skilled at establishing robust, properly managed, cross-border structures for business and personal assets that ensure protection.
          p.title analysis & risk assessment of existing  wealth structures
          p.regular Analysis and risk assessment is for clients that have an existing structure such as a foundation, trust, insurance wrap…  Years of experience in performing assessments for clients teaches us that  wealth structures may not be doing what the client believes that the wealth structure should be doing.  In such cases the consequence can be extreme and usually no one thought that it would happen to them.  An independent check of an existing wealth structure is wealth preservation.  An assessment can be focused on one aspect or one particular asset of the structure or it can encompass the entire wealth structure including tax assessment.
          p.title setting up holding structure for personal or business assets
          p.regular A holding structure has benefits to certain individuals and families whether due to tax, logistical complexity or as part of a financial engineering design.  We listen, assess and suggest a plan that is tailored to each individual or family.  Holding structures are an efficient way to manage all assets which helps the client to manage their time more effectively.
          p.title setting up holding structure for personal or business assets
          p.regular The information and services disclosed on this website are strictly for informational purposes only and are not intended by Elgin, nor should it be construed by any person, to be an offer, promotion, solicitation or recommendation on legal advice, loan advice, investment advice or tax advice.  Elgin is not a financial service provider, lender, tax advisor, law office or a real estate agent.  Elgin facilitates introductions in respect of services which are not regulated by the Financial Conduct Authority.
    .row
      .columns
        h2.section-header
          | other services
  .carousel-container
    .navigation
      .carousel-slider-prev
        = inline_svg "icons/arrow-left.svg"
      .carousel-slider-next
        = inline_svg "icons/arrow-right.svg"
    ul.carousel
      li
        .square
          a.mobile-link href=service_one_path
          .inner-wrapper
            .img style="background-image: url(#{asset_path('photos/service-background-1.jpg')})"
            .hover-color
            p.big-number 1
            .text
              p.title wealth structuring
              p.regular This text comes visible when hover on block!
              a href=service_one_path
                = inline_svg "icons/arrow-right.svg"
      li
        .square
          a.mobile-link href=service_one_path
          .inner-wrapper
            .img style="background-image: url(#{asset_path('photos/service-background-2.jpg')})"
            .hover-color
            p.big-number 2
            .text
              p.title succession planning
              p.regular This text comes visible when hover on block!
              a href=service_one_path
                = inline_svg "icons/arrow-right.svg"
      li
        .square
          a.mobile-link href=service_one_path
          .inner-wrapper
            .img style="background-image: url(#{asset_path('photos/service-background-3.jpg')})"
            .hover-color
            p.big-number 3
            .text
              p.title taxes
              p.regular This text comes visible when hover on block!
              a href=service_one_path
                = inline_svg "icons/arrow-right.svg"
      li
        .square
          a.mobile-link href=service_one_path
          .inner-wrapper
            .img style="background-image: url(#{asset_path('photos/service-background-4.jpg')})"
            .hover-color
            p.big-number 4
            .text
              p.title real estate
              p.regular This text comes visible when hover on block!
              a href=service_one_path
                = inline_svg "icons/arrow-right.svg"
      li
        .square
          a.mobile-link href=service_one_path
          .inner-wrapper
            .img style="background-image: url(#{asset_path('photos/service-background-5.jpg')})"
            .hover-color
            p.big-number 5
            .text
              p.title asset finance
              p.regular This text comes visible when hover on block!
              a href=service_one_path
                = inline_svg "icons/arrow-right.svg"
      li
        .square
          a.mobile-link href=service_one_path
          .inner-wrapper
            .img style="background-image: url(#{asset_path('photos/service-background-6.jpg')})"
            .hover-color
            p.big-number 6
            .text
              p.title credit finance
              p.regular This text comes visible when hover on block!
              a href=service_one_path
                = inline_svg "icons/arrow-right.svg"
      li
        .square
          a.mobile-link href=service_one_path
          .inner-wrapper
            .img style="background-image: url(#{asset_path('photos/service-background-7.jpg')})"
            .hover-color
            p.big-number 7
            .text
              p.title family office
              p.regular This text comes visible when hover on block!
              a href=service_one_path
                = inline_svg "icons/arrow-right.svg"
      li
        .square
          a.mobile-link href=service_one_path
          .inner-wrapper
            .img style="background-image: url(#{asset_path('photos/service-background-8.jpg')})"
            .hover-color
            p.big-number 8
            .text
              p.title coming soon
              p.regular This text comes visible when hover on block!
              a href=service_one_path
                = inline_svg "icons/arrow-right.svg"